package me.jericraft;

import org.bukkit.ChatColor;
import org.bukkit.Material;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;

import java.util.Arrays;

import static me.jericraft.main_menu.createGuiItem;

public class category_Miscellaneous {
    public static Inventory miscellaneous_1 = org.bukkit.Bukkit.createInventory(null, 54, ChatColor.RED + "Miscellaneous (page 1)");
    public static void addItems_Miscellaneous_1() {
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.BEACON));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.TURTLE_EGG));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.CONDUIT));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.SCUTE));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.COAL));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.CHARCOAL));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.DIAMOND));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.IRON_INGOT));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.GOLD_INGOT));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.STICK));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.BOWL));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.STRING));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.FEATHER));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.GUNPOWDER));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.WHEAT_SEEDS));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.WHEAT));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.FLINT));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.BUCKET));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.WATER_BUCKET));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.LAVA_BUCKET));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.SNOWBALL));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.LEATHER));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.PUFFERFISH_BUCKET));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.SALMON_BUCKET));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.COD_BUCKET));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.TROPICAL_FISH_BUCKET));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.BRICK));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.CLAY_BALL));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.SUGAR_CANE));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.KELP));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.PAPER));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.BOOK));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.SLIME_BALL));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.EGG));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.GLOWSTONE_DUST));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.INK_SAC));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.ROSE_RED));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.CACTUS_GREEN));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.COCOA_BEANS));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.LAPIS_LAZULI));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.PURPLE_DYE));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.CYAN_DYE));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.LIGHT_GRAY_DYE));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.GRAY_DYE));
        miscellaneous_1.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.PINK_DYE));
        ItemStack previousPage = new ItemStack(Material.WITHER_SKELETON_SKULL);
        ItemMeta previousPageMeta = previousPage.getItemMeta();
        previousPageMeta.setDisplayName("previous_page");
        previousPageMeta.setLore(Arrays.asList("<<-- (menu) Previous Page"));
        previousPage.setItemMeta(previousPageMeta);
        miscellaneous_1.setItem(45, new ItemStack(previousPage));
        ItemStack nextPage = new ItemStack(Material.WITHER_SKELETON_SKULL);
        ItemMeta nextPageMeta = nextPage.getItemMeta();
        nextPageMeta.setDisplayName("next_page");
        nextPageMeta.setLore(Arrays.asList("Next Page (2) -->>"));
        nextPage.setItemMeta(nextPageMeta);
        miscellaneous_1.setItem(53, new ItemStack(nextPage));
    }
    public static Inventory miscellaneous_2 = org.bukkit.Bukkit.createInventory(null, 54, ChatColor.RED + "Miscellaneous (page 2)");
    public static void addItems_Miscellaneous_2() {
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.LIME_DYE));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.DANDELION_YELLOW));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.LIGHT_BLUE_DYE));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.MAGENTA_DYE));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.ORANGE_DYE));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.BONE_MEAL));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.BONE));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.SUGAR));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.PUMPKIN_SEEDS));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.MELON_SEEDS));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.ENDER_PEARL));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.BLAZE_ROD));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.GOLD_NUGGET));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.NETHER_WART));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.ENDER_EYE));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.BAT_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.BLAZE_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.CAVE_SPIDER_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.CHICKEN_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.COD_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.COW_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.CREEPER_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.DOLPHIN_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.DONKEY_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.DROWNED_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.ELDER_GUARDIAN_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.ENDERMAN_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.ENDERMITE_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.EVOKER_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.GHAST_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.GUARDIAN_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.HORSE_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.HUSK_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.LLAMA_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.MAGMA_CUBE_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.MOOSHROOM_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.MULE_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.OCELOT_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.PARROT_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.PHANTOM_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.PIG_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.POLAR_BEAR_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.PUFFERFISH_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.RABBIT_SPAWN_EGG));
        miscellaneous_2.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.SALMON_SPAWN_EGG));
        ItemStack previousPage = new ItemStack(Material.WITHER_SKELETON_SKULL);
        ItemMeta previousPageMeta = previousPage.getItemMeta();
        previousPageMeta.setDisplayName("previous_page");
        previousPageMeta.setLore(Arrays.asList("<<-- (1) Previous Page"));
        previousPage.setItemMeta(previousPageMeta);
        miscellaneous_2.setItem(45, new ItemStack(previousPage));
        ItemStack nextPage = new ItemStack(Material.WITHER_SKELETON_SKULL);
        ItemMeta nextPageMeta = nextPage.getItemMeta();
        nextPageMeta.setDisplayName("next_page");
        nextPageMeta.setLore(Arrays.asList("Next Page (3) -->>"));
        nextPage.setItemMeta(nextPageMeta);
        miscellaneous_2.setItem(53, new ItemStack(nextPage));
    }
    public static Inventory miscellaneous_3 = org.bukkit.Bukkit.createInventory(null, 54, ChatColor.RED + "Miscellaneous (page 3)");
    public static void addItems_Miscellaneous_3() {
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.SHEEP_SPAWN_EGG));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.SHULKER_SPAWN_EGG));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.SILVERFISH_SPAWN_EGG));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.SKELETON_SPAWN_EGG));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.SKELETON_HORSE_SPAWN_EGG));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.SLIME_SPAWN_EGG));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.SPIDER_SPAWN_EGG));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.SQUID_SPAWN_EGG));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.STRAY_SPAWN_EGG));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.TROPICAL_FISH_SPAWN_EGG));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.TURTLE_EGG));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.VEX_SPAWN_EGG));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.VILLAGER_SPAWN_EGG));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.VINDICATOR_SPAWN_EGG));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.WITCH_SPAWN_EGG));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.WITHER_SKELETON_SPAWN_EGG));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.WOLF_SPAWN_EGG));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.ZOMBIE_SPAWN_EGG));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.ZOMBIE_HORSE_SPAWN_EGG));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.ZOMBIE_PIGMAN_SPAWN_EGG));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.EXPERIENCE_BOTTLE));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.FIRE_CHARGE));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.WRITABLE_BOOK));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.EMERALD));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.MAP));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.NETHER_STAR));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.FIREWORK_ROCKET));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.FIREWORK_STAR));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.NETHER_BRICK));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.QUARTZ));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.PRISMARINE_SHARD));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.PRISMARINE_CRYSTALS));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.RABBIT_HIDE));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.IRON_HORSE_ARMOR));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.GOLDEN_HORSE_ARMOR));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.DIAMOND_HORSE_ARMOR));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.CHORUS_FRUIT));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.POPPED_CHORUS_FRUIT));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.BEETROOT_SEEDS));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.SHULKER_SHELL));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.IRON_NUGGET));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.MUSIC_DISC_13));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.MUSIC_DISC_CAT));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.MUSIC_DISC_BLOCKS));
        miscellaneous_3.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.MUSIC_DISC_CHIRP));
        ItemStack previousPage = new ItemStack(Material.WITHER_SKELETON_SKULL);
        ItemMeta previousPageMeta = previousPage.getItemMeta();
        previousPageMeta.setDisplayName("previous_page");
        previousPageMeta.setLore(Arrays.asList("<<-- (2) Previous Page"));
        previousPage.setItemMeta(previousPageMeta);
        miscellaneous_3.setItem(45, new ItemStack(previousPage));
        ItemStack nextPage = new ItemStack(Material.WITHER_SKELETON_SKULL);
        ItemMeta nextPageMeta = nextPage.getItemMeta();
        nextPageMeta.setDisplayName("next_page");
        nextPageMeta.setLore(Arrays.asList("Next Page (4) -->>"));
        nextPage.setItemMeta(nextPageMeta);
        miscellaneous_3.setItem(53, new ItemStack(nextPage));
    }
    public static Inventory miscellaneous_4 = org.bukkit.Bukkit.createInventory(null, 27, ChatColor.RED + "Miscellaneous (page 4)");
    public static void addItems_Miscellaneous_4() {
        miscellaneous_4.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.MUSIC_DISC_FAR));
        miscellaneous_4.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.MUSIC_DISC_MALL));
        miscellaneous_4.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.MUSIC_DISC_MELLOHI));
        miscellaneous_4.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.MUSIC_DISC_STAL));
        miscellaneous_4.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.MUSIC_DISC_STRAD));
        miscellaneous_4.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.MUSIC_DISC_WARD));
        miscellaneous_4.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.MUSIC_DISC_11));
        miscellaneous_4.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.MUSIC_DISC_WAIT));
        miscellaneous_4.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.NAUTILUS_SHELL));
        miscellaneous_4.addItem(createGuiItem(ChatColor.BLUE + "item name", Material.HEART_OF_THE_SEA));
        ItemStack previousPage = new ItemStack(Material.WITHER_SKELETON_SKULL);
        ItemMeta previousPageMeta = previousPage.getItemMeta();
        previousPageMeta.setDisplayName("previous_page");
        previousPageMeta.setLore(Arrays.asList("<<-- (3) Previous Page"));
        previousPage.setItemMeta(previousPageMeta);
        miscellaneous_4.setItem(18, new ItemStack(previousPage));
    }
}