###########################################
# JeriCraft Shop GUI config file.
# Copyright 2018 Chalwk (Jericho Crosby), jericho.crosby227@gmail.com.
###########################################################################

PluginPrefix: "&7[&cJeriCraft&7]"
NoPermission: "&cAccess Denied."
ReloadPlugin: "&aPlugin Reloaded"
GamemodeNotice: '&cYou must be in survival mode!'

# Buy: right click
# sell: left click

buyRClick: '&bYou bought &e%item_quantity% %item_name% &bfor &e$%item_price%'
sellLClick: '&bYou sold &e%item_quantity% %item_name% &bfor &e$%item_price%'
buyRShiftClick: '&bYou bought &e%item_quantity% %item_name% &bfor &e$%item_price%'
sellLShiftClick: '&bYou sold &e%item_quantity% %item_name% &bfor &e$%item_price%'
notEnoughMoney: '&cNot Enough Money. You need a minimum of $%item_price% to buy %item_name%.'