###########################################
# JeriCraft Shop GUI config file.
# Copyright 2018 Chalwk (Jericho Crosby), jericho.crosby227@gmail.com.
###########################################################################

PluginPrefix: "&7[&cJeriCraft&7]"
NoPermission: "&cAccess Denied."
ReloadPlugin: "&aPlugin Reloaded"
GamemodeNotice: '&cYou must be in survival mode!'

# Buy: right click
# sell: left click

buyRClick: '&bYou bought &e%item_quantity% %item_name% &bfor &e$%item_price%'
sellLClick: '&bYou sold &e%item_quantity% %item_name% &bfor &e$%item_price%'
buyRShiftClick: '&bYou bought &e%item_quantity% %item_name% &bfor &e$%item_price%'
sellLShiftClick: '&bYou sold &e%item_quantity% %item_name% &bfor &e$%item_price%'
notEnoughMoney: '&cNot Enough Money! You need $%item_price% for X%item_quantity% %item_name%.'
notEnoughItems: "&cYou don't have enough items to sell!"
inventoryFull: '&cYour inventory was full! Items(s) have dropped on the ground.'